return {}
--
-- return {
--   "rachartier/tiny-inline-diagnostic.nvim",
--   config = function()
--     vim.diagnostic.config { virtual_text = false }
--     require("tiny-inline-diagnostic").setup {
--       options = {
--         show_source = true,
--       },
--     }
--   end,
-- }
